In [1]:
import numpy as np

In [2]:
def sigmoid(z):
  return 1 / (1 + np.exp(-z))

In [3]:
def logistic_sigmoid_regression(X, y, alpha, tol = 1e-4, loop = 10000):
    # w = [w_init]
    N = X.shape[1]
    d = X.shape[0]
    print(d)
    w = [np.random.rand(d, 1)]
    print(w[0])
    count = 0
    check_w = 20
    while count < loop:
        # mix data
        mix_id = np.random.permutation(N)
        for i in mix_id:
            xi = X[:, i].reshape(d, 1)
            yi = y[i]
            zi = sigmoid(np.dot(w[-1].T, xi))
            w_new = w[-1] + alpha*(yi - zi)*xi
            count += 1
            # stopping criteria
            if count%check_w == 0:
                if np.linalg.norm(w_new - w[-check_w]) < tol:
                    return w
            w.append(w_new)
    return w

#Bai tap 2

In [4]:
# Iris setosa = 0; Iris virginica = 1
X = np.array([[5.1, 3.5, 1.4, 0.2],
 [4.9, 3, 1.4, 0.2],
 [4.7, 3.2, 1.3, 0.2],
 [4.6, 3.1, 1.5, 0.2],
 [5, 3.6, 1.4, 0.2],
 [5.4, 3.9, 1.7, 0.4],
 [4.6, 3.4, 1.4, 0.3],
 [5, 3.4, 1.5, 0.2],
 [4.4, 2.9, 1.4, 0.2],
 [4.9, 3.1, 1.5, 0.1],
 [6.3, 3.3, 6, 2.5],
 [5.8, 2.7, 5.1, 1.9],
 [7.1, 3, 5.9, 2.1],
 [6.3, 2.9, 5.6, 1.8],
 [6.5, 3, 5.8, 2.2],
 [7.6, 3, 6.6, 2.1],
 [4.9, 2.5, 4.5, 1.7],
 [7.3, 2.9, 6.3, 1.8],
 [6.7, 2.5, 5.8, 1.8],
 [7.2, 3.6, 6.1, 2.5]])

y = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [5]:
alpha = 0.1
thetas = logistic_sigmoid_regression(X.T, y, alpha)

4
[[0.72972775]
 [0.52753871]
 [0.34228834]
 [0.08769895]]


In [6]:
theta = thetas[-1]
print(theta.shape)
print(theta)
print(thetas[4])

(4, 1)
[[-1.25896798]
 [-2.19263232]
 [ 3.43582151]
 [ 1.72973046]]
[[-0.31702902]
 [-0.15559327]
 [ 0.04909568]
 [ 0.04441886]]


##Predict

In [7]:
def predict(theta, x_test):
  return sigmoid(np.dot(theta.T, x_test))

In [8]:
print(predict(theta, [5.1,3.5,1.4,0.2]))
print(predict(theta, [7.2, 3.6, 6.1, 2.5]))

[0.00013117]
[0.99975763]
